version: '3.8'

services:
  base:
    build:
      context: ./path/to/base/Dockerfile # Update with the path to your Dockerfile directory for base image
    image: chatwoot/chatwoot:latest
    volumes:
      - /data/storage:/app/storage
    env_file: .env

  rails:
    build:
      context: ./path/to/rails/Dockerfile # Update with the path to your Dockerfile directory if different from base
    image: chatwoot/chatwoot:rails-latest
    depends_on:
      - postgres
      - redis
    ports:
      - '127.0.0.1:3000:3000'
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']
    volumes:
      - /data/storage:/app/storage
    env_file: .env

  sidekiq:
    build:
      context: ./path/to/sidekiq/Dockerfile # Update with the path to your Dockerfile directory if different from base
    image: chatwoot/chatwoot:sidekiq-latest
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']
    volumes:
      - /data/storage:/app/storage
    env_file: .env

  postgres:
    image: postgres:12
    restart: always
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chatwoot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD= # Please provide your password
    ports:
      - '127.0.0.1:5432:5432'

  redis:
    image: redis:alpine
    restart: always
    command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
    volumes:
      - /data/redis:/data
    env_file: .env
    ports:
      - '127.0.0.1:6379:6379'

